# Generated by Django 2.2.7 on 2019-11-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subjects', models.CharField(choices=[('biology_geography', 'Biology and Geography'), ('biology_chemistry', 'Biology and Chemistry'), ('whistory_geography', 'World history and Geography'), ('whistory_law', 'World history and Law'), ('geography_flanguage', 'Geography and Foreign language'), ('geography_math', 'Geography and Math'), ('flanguage_whistory', 'Foreign language and World history'), ('language_literature', 'Kazakh/Russian language and Kazakh/Russian literature'), ('kazlanguage_kazliterature', 'Kazakh language and Kazakh literature'), ('math_physics', 'Math and Physics'), ('rulanguage_reliterature', 'Russian language and Russian literature'), ('creativity_exam', 'Creativity exam'), ('chemistry_physics', 'Chemistry and Physics')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='core.City')),
                ('specialties', models.ManyToManyField(related_name='universities', to='core.Speciality')),
            ],
        ),
    ]
