# Generated by Django 2.2.7 on 2019-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191125_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='title_kaz',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='title_ru',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title_kaz',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title_ru',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='title_kaz',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='title_ru',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='title_eng',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='title_eng',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='title_eng',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
